name: Continuous Integration

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  jvm-tests:
    name: JVM tests (scala-${{ matrix.scala }}, jdk-${{ matrix.java }})
    strategy:
      fail-fast: true      
      matrix:
        os: [ubuntu-20.04]
        java: [8, 11]
        scala: [2.12.11, 2.13.2]
        command: ["ci-jvm"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: "adopt@1.${{ matrix.java }}"

      - name: sbt ++${{ matrix.scala }} ${{ matrix.command }}
        run: |
          ./.github/scripts/build.sh
        env:
          SCALA_VERSION: ${{ matrix.scala }}
          SBT_COMMAND: ${{ matrix.command }}

  js-tests:
    name: JS tests (scala-${{ matrix.scala }}, scalajs-${{ matrix.scalajs }}, jdk-${{ matrix.java }})
    strategy:
      fail-fast: true      
      matrix:
        os: [ubuntu-20.04]
        java: [adopt@1.11]
        scala: [2.12.11, 2.13.2]
        scalajs: [0.6.33, 1.1.0]
        command: [ci-js]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: "adopt@1.${{ matrix.java }}"

      - name: sbt ++${{ matrix.scala }} ${{ matrix.command }}
        run: |
          ./.github/scripts/build.sh
        env:
          SCALA_VERSION: ${{ matrix.scala }}
          SCALAJS_VERSION: ${{ matrix.scalaJS }}
          SBT_COMMAND: ${{ matrix.command }}

  package-tests:
    name: Package tests (scala-${{ matrix.scala }}, scalajs-${{ matrix.scalajs }}, jdk-${{ matrix.java }})
    strategy:
      fail-fast: true      
      matrix:
        os: [ubuntu-20.04]
        java: [adopt@1.11]
        scala: [2.12.11, 2.13.2]
        scalajs: [0.6.33, 1.1.0]
        command: [package]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: "adopt@1.${{ matrix.java }}"

      - name: sbt ++${{ matrix.scala }} ${{ matrix.command }}
        run: |
          ./.github/scripts/build.sh
        env:
          SCALA_VERSION: ${{ matrix.scala }}
          SCALAJS_VERSION: ${{ matrix.scalaJS }}
          SBT_COMMAND: ${{ matrix.command }}

  doc-tests:
    name: Doc tests (scala-${{ matrix.scala }}, scalajs-${{ matrix.scalajs }}, jdk-${{ matrix.java }})
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04]
        java: [adopt@1.11]
        scala: [2.13.2]
        scalajs: [1.1.0]
        command: ["ci-doc"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: "adopt@1.${{ matrix.java }}"

      - name: Set up Ruby 2.6 (for microsite)
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install microsite dependencies
        run: |
          bundle install --system --gemfile=site/Gemfile

      - name: sbt ++${{ matrix.scala }} ${{ matrix.command }}
        run: |
          ./.github/scripts/build.sh
        env:
          SCALA_VERSION: ${{ matrix.scala }}
          SCALAJS_VERSION: ${{ matrix.scalaJS }}
          SBT_COMMAND: ${{ matrix.command }}
